# This is the Python Code for Chapter2 ''Statistical Learning"

## 2.3.1 Basic Commands

In [118]:
import numpy as np  # for calculation purpose, let use np.array 
import random # for the random 

x = np.array([1, 3, 2, 5])
print x

[1 3 2 5]


In [119]:
x = np.array([1, 6, 2])
print x
y = [1, 4, 3]

[1 6 2]


In [120]:
len(x)  # use len() to find length of a vector

3

In [121]:
len(y)

3

In [122]:
print(x + y) # please note that we define x and y a little bit differently, but we still can do the calculation 
y = np.array([1, 4, 3])

[ 2 10  5]


In [123]:
whos

Variable   Type       Data/Info
-------------------------------
mu         int        0
np         module     <module 'numpy' from '/Us<...>ages/numpy/__init__.pyc'>
random     module     <module 'random' from '/U<...>ib/python2.7/random.pyc'>
sigma      int        1
x          ndarray    3: 3 elems, type `int64`, 24 bytes
y          ndarray    3: 3 elems, type `int64`, 24 bytes


In [124]:
del x # reset_selective x

In [125]:
%whos

Variable   Type       Data/Info
-------------------------------
mu         int        0
np         module     <module 'numpy' from '/Us<...>ages/numpy/__init__.pyc'>
random     module     <module 'random' from '/U<...>ib/python2.7/random.pyc'>
sigma      int        1
y          ndarray    3: 3 elems, type `int64`, 24 bytes


In [126]:
reset?

In [127]:
x = [[1,2],[3, 4]]
print x

[[1, 2], [3, 4]]


In [128]:
x = np.array([1, 2, 3, 4])

In [129]:
x = np.reshape(x, [2,2])
print x

[[1 2]
 [3 4]]


In [130]:
np.sqrt(x)

x**2
np.square(x)

array([[ 1,  4],
       [ 9, 16]])

In [131]:
mu, sigma = 0, 1
x = np.random.normal(mu, sigma, 50)
y = x + np.random.normal(50, 0.1, 50)
print x, y

[-0.46691314  0.8342022   0.21429247  0.99973705 -0.40455975  0.88927353
  0.55187197 -1.73578717  0.64367456  1.03957614  0.90050456 -0.65707986
  2.23132096 -2.15669623 -0.33842074 -1.19855303 -0.41247541 -0.97402159
 -0.30070862  0.1615199  -1.39787823  0.24423731  1.01805546 -1.70830743
  0.48505175  0.37324811 -2.42310732 -0.28496097  0.30896662  0.34206544
  0.69141161 -0.11021055  0.34794409 -1.34580104  0.36789912  0.47226891
 -1.33768362  0.71906597  0.87721576  0.90681044 -0.20094611 -0.21176003
 -0.60635944  0.94002898 -1.68031684 -1.19349299  0.16071839  0.76713821
 -0.42233691  0.04958895] [ 49.66517009  50.8522436   50.12066133  50.96324289  49.7843991
  50.94488102  50.7030287   48.11026196  50.69274606  50.93381299
  50.84760731  49.36800603  52.18994442  47.69661313  49.57298498
  48.92317339  49.61945559  49.0239575   49.63075619  50.1407498
  48.59516952  50.26130422  50.94961183  48.24208643  50.47690391
  50.47036547  47.55575635  49.69870746  50.23591217  50.43619

In [132]:
np.corrcoef(x, y) # this will return the correlation matrix 

array([[ 1.        ,  0.99567641],
       [ 0.99567641,  1.        ]])

In [133]:
np.corrcoef(x, y)[0,1]

0.9956764109898455

In [134]:
import random 
random.seed(2333)

In [135]:
np.random.normal(mu, sigma, 50) # after set up the seed, this should genernate the same result

array([-0.20471011,  1.35384795, -1.02183393, -1.15899606, -0.61574513,
       -1.14966738,  0.12247596, -1.2825328 , -0.94014259,  0.78546441,
       -0.57490017,  0.0630337 ,  0.315595  , -0.32821054, -1.28716109,
        0.90740826, -0.03508222,  2.60942501, -1.42189242,  0.58918535,
       -0.57863109,  0.23313748,  1.16387239,  1.31001639,  0.21537062,
       -0.97740245,  0.08015641,  0.82685159,  1.09665363,  1.52686385,
       -0.87379505,  0.03878198,  0.78661422,  0.68444601,  0.71109785,
        0.15431068,  0.16793029,  0.38062528, -0.33710595, -1.92486181,
        2.11459646, -0.40796197, -0.66721093,  0.33512386,  1.8004164 ,
        1.26791524, -0.7275932 ,  0.1259763 ,  0.42585775, -0.6561076 ])

In [136]:
y = np.random.normal(mu, sigma, 100)

In [137]:
print np.mean(y)

0.257754125931


In [138]:
print np.var(y)

0.902767232824


In [139]:
print np.sqrt(np.var(y))
print np.std(y)

0.950140638445
0.950140638445


In [140]:
y = np.random.normal(mu, sigma, 5000) # if we raise the number of sample to a larger number, the mean and std will be more close to (0, 1)
print np.mean(y)
print np.std(y)

-0.0068755893488
1.00594709381
